[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "StarAppBuilder"
version = "0.1.1"
description = "Starlight App Builder"
requires-python = ">=3.9"
dependencies = ["tqdm"]

[project.scripts]
star_app_builder = "star_app_builder.cli:main"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/star_app_builder"]